version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "Bot"
    groups:
      npm:
        patterns:
          - '*'
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "Bot"
    groups:
      github-actions:
        patterns:
          - '*'

