version = 1
test_patterns = ["**/tests/**"]

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["jquery"]

[[analyzers]]
name = "python"

  [analyzers.meta]
  runtime_version = "3.x.x"