ci:
  autoupdate_schedule: quarterly
repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v9.24.0'
    hooks:
      - id: eslint
        additional_dependencies:
            - "eslint@v9.17.0"
            - "@eslint/js@v9.17.0"
            - "globals"
        files: \.js?$
        types: [file]
        args:
        - --fix
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.4"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

